### PR TITLE
Fix reading setting of keyboard backlight

### PR DESCRIPTION
**Pull request by wl2776**
1. Add reading settings of keyboard backlight so that `cat` from rgb zones return correct values at first load

2. Add draft of experiments with <kbd>Omen</kbd> key.

### CODE REVIEW

**Comment by markozajc** [comment]
Pressing the Omen key seems to still throw a `bad event status 0x5` for me.

**Comment by wl2776** [comment]
> Pressing the Omen key seems to still throw a `bad event status 0x5` for me.

It works on my HP Omen 15, manufactured in 2020. 

In my case I was receiving message "Unknown event_id - 1d". I've found respective message in sources and have figured out how to process it.

In your case something was not found. 
`bad event status 0x5` is printed at line 552 in processing of result returned by `wmi_get_event_data`

You can see this function here:  https://elixir.bootlin.com/linux/latest/source/drivers/platform/x86/wmi.c#L607

Its bottom line is `return AE_NOT_FOUND`. Value of this macro is 5.

**Comment by pelrun** [comment]
I'd recommend not hard-coding the Omen key to an existing function. It's possible to emit a custom keycode which can then be configured using setkeycode in userspace (I already use `setkeycodes e057 240 e058 240` to fix the incorrect lid open/close behaviour.)

**Comment by wl2776** [comment]
> I'd recommend not hard-coding the Omen key to an existing function. It's possible to emit a custom keycode which can then be configured using setkeycode in userspace

I am new to kernel development. Is there any table listing keycodes in the world?

**Comment by wl2776** [comment]
I'll be back :)

**Comment by pelrun** [comment]
I did a bit of idle digging yesterday and discovered I can decompile the ACPI bytecode that implements the WMI commands/events that the kernel module is interfacing with. It's answered a few questions I had about the led control, but opened up another can of worms for the hotkey stuff.

@wl2776, any chance you could dump the acpi firmware of your laptop for comparison purposes, since yours is behaving differently to mine/markozajc? The command would be `sudo acpidump > acpidump.hex` (obviously you'll need to install acpidump first.)

**Comment by wl2776** [comment]
> @wl2776, any chance you could dump the acpi firmware of your laptop for comparison purposes

Done, have sent to the email address in your profile.

**Pull request closed without merging**
